package modelo;
// Generated 12/04/2016 01:41:32 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idusuario;
     private String nombre;
     private String app;
     private String apm;
     private String correo;
     private String facultad;
     private String telefono;
     private byte[] fotoUsr;
     private String contrasenia;
     private Set solicitudeses = new HashSet(0);
     private Set libros = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public Usuario(int idusuario, String nombre, String app, String apm, String correo, String facultad, String telefono, byte[] fotoUsr, String contrasenia, Set solicitudeses, Set libros) {
       this.idusuario = idusuario;
       this.nombre = nombre;
       this.app = app;
       this.apm = apm;
       this.correo = correo;
       this.facultad = facultad;
       this.telefono = telefono;
       this.fotoUsr = fotoUsr;
       this.contrasenia = contrasenia;
       this.solicitudeses = solicitudeses;
       this.libros = libros;
    }
   
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApp() {
        return this.app;
    }
    
    public void setApp(String app) {
        this.app = app;
    }
    public String getApm() {
        return this.apm;
    }
    
    public void setApm(String apm) {
        this.apm = apm;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getFacultad() {
        return this.facultad;
    }
    
    public void setFacultad(String facultad) {
        this.facultad = facultad;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public byte[] getFotoUsr() {
        return this.fotoUsr;
    }
    
    public void setFotoUsr(byte[] fotoUsr) {
        this.fotoUsr = fotoUsr;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public Set getSolicitudeses() {
        return this.solicitudeses;
    }
    
    public void setSolicitudeses(Set solicitudeses) {
        this.solicitudeses = solicitudeses;
    }
    public Set getLibros() {
        return this.libros;
    }
    
    public void setLibros(Set libros) {
        this.libros = libros;
    }




}


